export interface PaginatedResult<T> { list: T[]; total: number; page: number; size: number; totalPages?: number }
export interface ScanRecord { id?: number; brxh?: string; bah?: string; sjh?: string; filename?: string; btype?: number | null; pages?: number | null; openerNo?: string; uploadDate?: string | null; uploadFlag?: number | null; folder?: string; ossUrl?: string; img_url?: string; fileSize?: number | null; checksumMd5?: string; migrationStatus?: string; migratedAt?: string | null }
export interface PatientRecord { id?: number; idCard?: string; bah?: string; name?: string; ruyuan?: string; admissiontime?: string; admissionTime?: string; department?: string; bingqu?: string; chuangwei?: string }
export interface StatisticsRecord { bah?: string; cid?: string; openerNo?: string; date?: string; type?: string; pages?: number; sjh?: string; patientname?: string; inpatientdepartment?: string; patientid?: string; dischargedate?: string }
export interface DateStatistics { date: string; recordCount?: number; totalPages?: number; pages?: number }
export interface StatisticsSummary { total?: { totalRecords?: number; totalPages?: number }; uniqueBAHCount?: number; byType?: Array<{ type?: string; recordCount?: number; totalPages?: number }> }
export interface DashboardData { overview?: Record<string, any>; uniqueBAHCount?: number; recentTrend?: DateStatistics[]; topBAH?: Array<{ bah?: string; recordCount?: number; totalPages?: number }> }
export interface LogRecord { id?: number; username?: string; clientIp?: string; requestUri?: string; method?: string; userAgent?: string; accessTime?: string; queryString?: string; requestBody?: string; responseStatus?: number; executeTime?: number | null; referer?: string; auditAction?: string; auditTarget?: string; auditDescription?: string }
export interface ImageAuditAnalytics { totalAccesses: number; uniqueUsers: number; uniqueTargets: number; abnormalAccesses: number; averageDurationMs: number; trend: Array<{ date: string; count: number }>; actionDistribution: Array<{ label: string; count: number }>; topUsers: Array<{ label: string; count: number }> }
export interface AuthUser { id?: number; username?: string; displayName?: string; roleCode?: string; roleName?: string; permissions?: string[]; status?: string; lastLoginAt?: string }
export interface AuthRole { code?: string; name?: string; description?: string; permissions?: string; sortOrder?: number }
export interface HealthInfo { status?: string; timestamp?: string; port?: string; application?: string; components?: Record<string, { status?: string; usagePercent?: string; error?: string }> }
export interface SystemOverview { info?: { application?: Record<string, string>; jvm?: Record<string, string | number>; operatingSystem?: Record<string, string> }; memory?: { heap?: Record<string, string>; nonHeap?: Record<string, string>; usagePercent?: string }; runtime?: Record<string, any>; health?: HealthInfo; properties?: Record<string, string>; gc?: Record<string, any>; threads?: Record<string, number> }
export type ArchiveBoxStatus = "NORMAL" | "MISSING" | "MISPLACED" | "CONFLICT" | "OTHER"
export interface ArchiveBoxRecord { id?: number; bah?: string; sjh?: string; boxNo?: string; expectedBoxNo?: string; status: ArchiveBoxStatus; remark?: string; createdAt?: string; updatedAt?: string }
export interface ArchiveBoxSummary { totalRecords: number; totalBoxes: number; missingCount: number; abnormalCount: number }
export interface ArchiveBoxGroup { boxNo: string; recordCount: number; abnormalCount: number; updatedAt?: string }
export interface MigrationStatistics { totalCount?: number; migratedCount?: number; pendingCount?: number; failedCount?: number; percentage?: number }
export interface MigrationLogRecord { id?: number; scanId?: number; localPath?: string; ossUrl?: string; migrationStatus?: string; errorMessage?: string; fileSize?: number; checksumMd5?: string; migratedAt?: string; verifiedAt?: string; createdAt?: string; updatedAt?: string }
export interface ResponseMetricAnalysis { overview: { totalRequests: number; frontendSampleCount?: number; successRate: number; avgServerDurationMs: number; avgClientDurationMs: number; p95ClientDurationMs: number }; trend: Array<{ bucket: string; requestCount: number; errorCount: number; avgServerDurationMs: number; avgClientDurationMs: number }>; slowEndpoints: Array<{ routePattern: string; method: string; requestCount: number; errorCount: number; avgServerDurationMs: number; avgClientDurationMs: number; p95ClientDurationMs: number }> }
export interface IdCardArchiveCase extends PatientRecord { patientRecordId?: number; sjh?: string }
export interface IdCardArchiveSearchResponse { token: string; maskedIdCard: string; cases: IdCardArchiveCase[] }
