import { useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Box, CircleAlert, FileArchive, Plus, Search, Trash2 } from "lucide-react"
import { toast } from "sonner"
import { archiveBoxesApi } from "@/api/mrr"
import { EmptyState, ErrorState, LoadingState } from "@/components/shared/data-state"
import { MetricCard } from "@/components/shared/metric-card"
import { PageHeader } from "@/components/shared/page-header"
import { Pager } from "@/components/shared/pager"
import { QueryCard, QueryField } from "@/components/shared/query-card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Textarea } from "@/components/ui/textarea"
import { formatDateTime } from "@/lib/utils"
import type { ArchiveBoxRecord, ArchiveBoxStatus } from "@/types/api"
const statuses: Array<{value:ArchiveBoxStatus;label:string}>=[{value:"NORMAL",label:"正常"},{value:"MISSING",label:"缺失"},{value:"MISPLACED",label:"存放在其他箱子"},{value:"CONFLICT",label:"箱号冲突"},{value:"OTHER",label:"其他异常"}]
const initial={bah:"",sjh:"",boxNo:"",expectedBoxNo:"",status:"NORMAL" as ArchiveBoxStatus,remark:""}
export function ArchiveBoxesPage(){
 const qc=useQueryClient();const[page,setPage]=useState(1),[size,setSize]=useState(100),[filters,setFilters]=useState({keyword:"",status:""}),[applied,setApplied]=useState(filters),[boxKeyword,setBoxKeyword]=useState("");const[dialog,setDialog]=useState(false),[editing,setEditing]=useState<ArchiveBoxRecord|null>(null),[form,setForm]=useState(initial)
 const summary=useQuery({queryKey:["box-summary"],queryFn:archiveBoxesApi.summary});const records=useQuery({queryKey:["box-records",page,size,applied],queryFn:()=>archiveBoxesApi.list({page,size,...applied})});const groups=useQuery({queryKey:["box-groups",boxKeyword],queryFn:()=>archiveBoxesApi.groups({page:1,size:200,keyword:boxKeyword||undefined})})
 const save=useMutation({mutationFn:()=>editing?.id?archiveBoxesApi.update(editing.id,form):archiveBoxesApi.create(form),onSuccess:()=>{toast.success("装箱记录已保存");setDialog(false);qc.invalidateQueries({queryKey:["box"]});qc.invalidateQueries({queryKey:["box-records"]});qc.invalidateQueries({queryKey:["box-summary"]})},onError:e=>toast.error(e.message)})
 const remove=useMutation({mutationFn:archiveBoxesApi.remove,onSuccess:()=>{toast.success("已删除");qc.invalidateQueries({queryKey:["box-records"]});qc.invalidateQueries({queryKey:["box-summary"]})},onError:e=>toast.error(e.message)})
 function open(row?:ArchiveBoxRecord){setEditing(row||null);setForm(row?{bah:row.bah||"",sjh:row.sjh||"",boxNo:row.boxNo||"",expectedBoxNo:row.expectedBoxNo||"",status:row.status,remark:row.remark||""}:initial);setDialog(true)}
 const s=summary.data||{totalRecords:0,totalBoxes:0,missingCount:0,abnormalCount:0}
 return <><PageHeader eyebrow="Archive Boxes" title="档案装箱" description="维护实体病案与箱号的对应关系，并集中追踪缺失、错箱和冲突。" actions={<Button onClick={()=>open()}><Plus/>新增记录</Button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="装箱病案" value={s.totalRecords} icon={FileArchive}/><MetricCard label="已用箱数" value={s.totalBoxes} icon={Box}/><MetricCard label="缺失病案" value={s.missingCount} icon={CircleAlert}/><MetricCard label="异常记录" value={s.abnormalCount} icon={CircleAlert}/></div>
 <Tabs defaultValue="records"><TabsList><TabsTrigger value="records">装箱记录</TabsTrigger><TabsTrigger value="boxes">箱号视图</TabsTrigger></TabsList><TabsContent value="records"><div className="space-y-4"><QueryCard><QueryField label="关键字"><Input value={filters.keyword} onChange={e=>setFilters({...filters,keyword:e.target.value})} placeholder="病案号 / 上架号 / 箱号"/></QueryField><QueryField label="状态"><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">全部状态</option>{statuses.map(i=><option key={i.value} value={i.value}>{i.label}</option>)}</select></QueryField><Button onClick={()=>{setApplied(filters);setPage(1)}}><Search/>查询</Button></QueryCard><Card>{records.isLoading?<LoadingState/>:records.error?<ErrorState error={records.error}/>:!records.data?.list.length?<EmptyState/>:<Table><TableHeader><TableRow><TableHead>病案号</TableHead><TableHead>上架号</TableHead><TableHead>实际箱号</TableHead><TableHead>应在箱号</TableHead><TableHead>状态</TableHead><TableHead>备注</TableHead><TableHead>更新时间</TableHead><TableHead className="w-24">操作</TableHead></TableRow></TableHeader><TableBody>{records.data.list.map(row=><TableRow key={row.id}><TableCell className="font-medium">{row.bah||"—"}</TableCell><TableCell>{row.sjh||"—"}</TableCell><TableCell>{row.boxNo||"—"}</TableCell><TableCell>{row.expectedBoxNo||"—"}</TableCell><TableCell><Badge variant={row.status==="NORMAL"?"success":row.status==="MISSING"?"destructive":"warning"}>{statuses.find(i=>i.value===row.status)?.label||row.status}</Badge></TableCell><TableCell className="max-w-56 truncate">{row.remark||"—"}</TableCell><TableCell>{formatDateTime(row.updatedAt)}</TableCell><TableCell><Button size="sm" variant="ghost" onClick={()=>open(row)}>编辑</Button><Button size="icon" variant="ghost" onClick={()=>row.id&&confirm("确认删除这条记录？")&&remove.mutate(row.id)}><Trash2/></Button></TableCell></TableRow>)}</TableBody></Table>}<Pager page={page} size={size} total={records.data?.total||0} onPageChange={setPage} onSizeChange={v=>{setSize(v);setPage(1)}}/></Card></div></TabsContent><TabsContent value="boxes"><div className="space-y-4"><QueryCard><QueryField label="箱号"><Input value={boxKeyword} onChange={e=>setBoxKeyword(e.target.value)} placeholder="筛选箱号"/></QueryField></QueryCard><Card>{groups.isLoading?<LoadingState/>:!groups.data?.list.length?<EmptyState/>:<div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4">{groups.data.list.map(box=><div key={box.boxNo} className="rounded-xl border p-4"><div className="flex items-center justify-between"><p className="font-semibold">{box.boxNo}</p><Box className="size-4 text-muted-foreground"/></div><p className="mt-3 text-2xl font-semibold">{box.recordCount}</p><p className="text-xs text-muted-foreground">病案记录 · 异常 {box.abnormalCount}</p></div>)}</div>}</Card></div></TabsContent></Tabs>
 <Dialog open={dialog} onOpenChange={setDialog}><DialogContent><DialogHeader><DialogTitle>{editing?"编辑装箱记录":"新增装箱记录"}</DialogTitle><DialogDescription>病案号或上架号至少填写一项。</DialogDescription></DialogHeader><div className="grid gap-4 py-2 sm:grid-cols-2">{(["bah","sjh","boxNo","expectedBoxNo"] as const).map(key=><div key={key} className="space-y-2"><Label>{({bah:"病案号",sjh:"上架号",boxNo:"实际箱号",expectedBoxNo:"应在箱号"} as const)[key]}</Label><Input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></div>)}<div className="space-y-2 sm:col-span-2"><Label>状态</Label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={form.status} onChange={e=>setForm({...form,status:e.target.value as ArchiveBoxStatus})}>{statuses.map(i=><option key={i.value} value={i.value}>{i.label}</option>)}</select></div><div className="space-y-2 sm:col-span-2"><Label>备注</Label><Textarea value={form.remark} onChange={e=>setForm({...form,remark:e.target.value})}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setDialog(false)}>取消</Button><Button disabled={save.isPending||(!form.bah&&!form.sjh)} onClick={()=>save.mutate()}>保存</Button></DialogFooter></DialogContent></Dialog></>
}
