import { useQuery } from "@tanstack/react-query"
import { Activity, Cpu, Database, HardDrive, MemoryStick, RefreshCw } from "lucide-react"
import { systemApi } from "@/api/mrr"
import { ErrorState, LoadingState } from "@/components/shared/data-state"
import { MetricCard } from "@/components/shared/metric-card"
import { PageHeader } from "@/components/shared/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
export function MonitoringPage(){const query=useQuery({queryKey:["system-overview"],queryFn:systemApi.overview,refetchInterval:30_000});if(query.isLoading)return <LoadingState/>;if(query.error)return <ErrorState error={query.error}/>;const d=query.data||{},info=d.info||{},health=d.health||{};return <><PageHeader eyebrow="Monitoring" title="系统监控" description="查看应用运行时间、JVM、内存、线程、GC 与依赖组件健康状态。" actions={<Button variant="outline" onClick={()=>query.refetch()}><RefreshCw/>刷新</Button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="应用状态" value={health.status||"UNKNOWN"} icon={Activity}/><MetricCard label="内存使用率" value={d.memory?.usagePercent||"—"} icon={MemoryStick}/><MetricCard label="当前线程" value={d.threads?.currentCount} icon={Cpu}/><MetricCard label="GC 次数" value={d.gc?.totalCollections} icon={HardDrive}/></div><div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle>应用与运行环境</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{Object.entries({...info.application,...info.jvm,...info.operatingSystem}).map(([key,value])=><div key={key} className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">{key}</p><p className="mt-1 break-all text-sm font-medium">{String(value??"—")}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>组件健康</CardTitle></CardHeader><CardContent className="space-y-3">{Object.entries(health.components||{}).map(([key,value])=><div key={key} className="flex items-center justify-between rounded-lg border p-3"><div className="flex items-center gap-2"><Database className="size-4"/><div><p className="text-sm font-medium">{key}</p><p className="text-xs text-muted-foreground">{value.usagePercent||value.error||""}</p></div></div><Badge variant={value.status==="UP"?"success":"destructive"}>{value.status||"UNKNOWN"}</Badge></div>)}</CardContent></Card></div><Card><CardHeader><CardTitle>系统属性</CardTitle></CardHeader><CardContent className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{Object.entries(d.properties||{}).map(([key,value])=><div key={key} className="rounded-md bg-muted/60 p-3"><p className="break-all font-mono text-[11px] text-muted-foreground">{key}</p><p className="mt-1 break-all text-xs">{value}</p></div>)}</CardContent></Card></>}
export function StatusPage(){const query=useQuery({queryKey:["public-health"],queryFn:systemApi.health,refetchInterval:30_000});return <div className="mx-auto max-w-4xl py-8"><PageHeader eyebrow="Service Status" title="服务状态" description="公开健康检查页面，每 30 秒自动刷新。"/><Card className="mt-8"><CardContent className="p-6">{query.isLoading?<LoadingState/>:query.error?<ErrorState error={query.error}/>:<><div className="flex items-center gap-3"><div className={`size-3 rounded-full ${query.data?.status==="UP"?"bg-emerald-500":"bg-red-500"}`}/><p className="text-xl font-semibold">{query.data?.application||"MRR"} · {query.data?.status||"UNKNOWN"}</p></div><p className="mt-2 text-sm text-muted-foreground">端口 {query.data?.port||"—"} · {query.data?.timestamp||"—"}</p><div className="mt-6 space-y-3">{Object.entries(query.data?.components||{}).map(([key,value])=><div key={key} className="flex items-center justify-between rounded-lg border p-4"><span>{key}</span><Badge variant={value.status==="UP"?"success":"destructive"}>{value.status||"UNKNOWN"}</Badge></div>)}</div></>}</CardContent></Card></div>}
